// src/routes/api.tsx
import * as React from 'react'
import { createFileRoute } from '@tanstack/react-router'
import {
  Clipboard,
  Code2,
  Copy,
  ExternalLink,
  Link as LinkIcon,
  Send,
  X,
} from 'lucide-react'
import { Select } from '@/components/base-select'
import { Tabs } from '@/components/base-tabs'
import { PageHero } from '@/components/page-hero'
import { Badge, Button, Card, CardContent, CardHeader, Input, StatusBadge } from '@/components/ui'
import { seoMeta } from '@/lib/seo'

export const Route = createFileRoute('/api')({
  head: () => ({
    meta: seoMeta({
      title: 'DNS.NF Public API - DNS Lookup API, Reverse IP API, DNSSEC API',
      description:
        'Use the DNS.NF Public API at https://api.dns.nf for DNS lookup, reverse IP, subdomain discovery, reverse NS, reverse MX, rDNS search, DNS history, and DNSSEC checks.',
      keywords: ['DNS API', 'public DNS API', 'DNS lookup API', 'reverse IP API', 'DNSSEC API', 'DNS查询API'],
    }),
  }),
  component: PublicApiPage,
})

const API_BASE = 'https://api.dns.nf'
const WEBSITE = 'https://dns.nf'

type ApiParam = {
  name: string
  type: string
  required?: boolean
  defaultValue: string
  description: string
}

type ApiEndpoint = {
  method: 'GET'
  path: string
  title: string
  description: string
  params: ApiParam[]
  response: string
  notes?: string[]
}

type ResponseState = {
  status: number
  contentType: string
  body: string
}

const endpoints: ApiEndpoint[] = [
  {
    method: 'GET',
    path: '/v1/dns/lookup',
    title: 'DNS Lookup',
    description: 'Resolve standard DNS records for domains, IPv4 addresses, or IPv4 CIDR targets.',
    params: [
      { name: 'domain', type: 'string', required: true, defaultValue: 'example.com', description: 'Domain name, IPv4 address, or IPv4 CIDR target. The API also accepts ip as an alias.' },
      { name: 'type', type: 'string', defaultValue: 'ALL', description: 'Record type: ALL, A, AAAA, CNAME, MX, NS, TXT, SOA, CAA, SRV, or PTR.' },
    ],
    response: `{
  "code": 0,
  "data": {
    "domain": "example.com",
    "records": {
      "A": ["93.184.216.34"],
      "MX": []
    }
  },
  "cached": false,
  "timestamp": 1783340000
}`,
    notes: ['Use type=ALL when you want the normalized record set shown in the DNS.NF console.', 'Public API examples use DNS.NF defaults and do not require provider selection.'],
  },
  {
    method: 'GET',
    path: '/v1/dns/reverse-ip',
    title: 'Reverse IP',
    description: 'Find public domains observed on the same IPv4 address using best-effort public datasets.',
    params: [{ name: 'ip', type: 'string', required: true, defaultValue: '8.8.8.8', description: 'IPv4 address to search.' }],
    response: `{
  "code": 0,
  "data": {
    "ip": "8.8.8.8",
    "total": 2,
    "domains": [
      { "name": "dns.google", "sources": ["hackertarget"] }
    ],
    "completeness": "best_effort_public_sources"
  },
  "cached": true,
  "timestamp": 1783340000
}`,
    notes: ['Results depend on public source availability and may be incomplete.', 'The website paginates large result sets for easier review.'],
  },
  {
    method: 'GET',
    path: '/v1/dns/subdomains',
    title: 'Subdomains',
    description: 'Discover observed subdomains for a registered domain.',
    params: [
      { name: 'domain', type: 'string', required: true, defaultValue: 'example.com', description: 'Root domain to inspect.' },
      { name: 'limit', type: 'integer', defaultValue: '200', description: 'Maximum number of returned rows. Server cap applies.' },
    ],
    response: `{
  "code": 0,
  "data": {
    "target": "example.com",
    "total": 1,
    "items": [
      { "name": "www.example.com", "sources": ["crtsh"] }
    ]
  },
  "cached": false,
  "timestamp": 1783340000
}`,
  },
  {
    method: 'GET',
    path: '/v1/dns/reverse-ns',
    title: 'Reverse NS',
    description: 'Find domains sharing authoritative name-server infrastructure.',
    params: [
      { name: 'domain', type: 'string', required: true, defaultValue: 'example.com', description: 'Domain whose NS records will be correlated.' },
      { name: 'limit', type: 'integer', defaultValue: '50', description: 'Maximum number of returned rows.' },
    ],
    response: `{
  "code": 0,
  "data": {
    "target": "example.com",
    "ns": ["ns1.example-dns.com"],
    "total": 1,
    "items": [
      { "domain": "sample.net", "shared_ns": ["ns1.example-dns.com"] }
    ]
  },
  "cached": false,
  "timestamp": 1783340000
}`,
  },
  {
    method: 'GET',
    path: '/v1/dns/reverse-mx',
    title: 'Reverse MX',
    description: 'Find domains sharing mail exchanger infrastructure.',
    params: [
      { name: 'domain', type: 'string', required: true, defaultValue: 'example.com', description: 'Domain whose MX records will be correlated.' },
      { name: 'limit', type: 'integer', defaultValue: '50', description: 'Maximum number of returned rows.' },
    ],
    response: `{
  "code": 0,
  "data": {
    "target": "example.com",
    "mx": ["mx1.example-mail.com"],
    "total": 1,
    "items": [
      { "domain": "sample.org", "shared_mx": ["mx1.example-mail.com"] }
    ]
  },
  "cached": false,
  "timestamp": 1783340000
}`,
  },
  {
    method: 'GET',
    path: '/v1/dns/rdns',
    title: 'rDNS Search',
    description: 'Search stored PTR records by keyword.',
    params: [
      { name: 'keyword', type: 'string', required: true, defaultValue: 'google', description: 'PTR keyword. Minimum length is 2 characters.' },
      { name: 'mode', type: 'string', defaultValue: 'middle', description: 'Search mode: left, middle, or right.' },
      { name: 'limit', type: 'integer', defaultValue: '200', description: 'Maximum number of returned records. Maximum accepted value is 1000.' },
    ],
    response: `{
  "code": 0,
  "data": {
    "keyword": "google",
    "mode": "middle",
    "total": 1,
    "records": [
      { "ip": "8.8.8.8", "ptr": "dns.google" }
    ]
  },
  "timestamp": 1783340000
}`,
  },
  {
    method: 'GET',
    path: '/v1/dns/dnssec',
    title: 'DNSSEC',
    description: 'Inspect DS, DNSKEY, RRSIG, and NSEC records with a simple security score.',
    params: [{ name: 'domain', type: 'string', required: true, defaultValue: 'example.com', description: 'Domain to inspect.' }],
    response: `{
  "code": 0,
  "data": {
    "domain": "example.com",
    "score": 100,
    "status": "strong",
    "records": {
      "DS": { "values": ["..."], "confidence": "high" }
    }
  },
  "cached": false,
  "timestamp": 1783340000
}`,
  },
  {
    method: 'GET',
    path: '/v1/dns/history',
    title: 'DNS History',
    description: 'Read passive DNS history records stored by DNS.NF.',
    params: [
      { name: 'domain', type: 'string', required: true, defaultValue: 'example.com', description: 'Domain to search.' },
      { name: 'limit', type: 'integer', defaultValue: '500', description: 'Maximum number of records. Maximum accepted value is 2000.' },
    ],
    response: `{
  "code": 0,
  "data": {
    "domain": "example.com",
    "total": 1,
    "records": [
      { "type": "A", "value": "104.16.132.229", "source": "local" }
    ]
  },
  "timestamp": 1783340000
}`,
  },
]

const languageLabels: Record<string, string> = {
  curl: 'cURL',
  javascript: 'JavaScript',
  python: 'Python',
  go: 'Go',
  php: 'PHP',
  java: 'Java',
}

const errorRows = [
  ['200', 'Request succeeded. The response body contains code, data, cached when applicable, and timestamp.'],
  ['400', 'Missing or invalid query parameter.'],
  ['404', 'No matching DNS or relationship records were found.'],
  ['405', 'Unsupported HTTP method. Public endpoints use GET.'],
  ['429', 'Rate limit exceeded. The public v1 API is limited to 60 requests per minute per client IP.'],
  ['500 / 502', 'Server or upstream source error. Retry later or reduce request scope.'],
] satisfies Array<readonly [string, string]>

const recordRows = [
  ['A', 'IPv4 address mapping'],
  ['AAAA', 'IPv6 address mapping'],
  ['CNAME', 'Alias target chain'],
  ['MX', 'Mail routing host and priority'],
  ['NS', 'Authoritative name servers'],
  ['TXT', 'SPF, DMARC, DKIM, and verification strings'],
  ['SOA', 'Zone authority metadata'],
  ['CAA', 'Allowed certificate authorities'],
  ['SRV', 'Service target, port, priority, and weight'],
  ['PTR', 'Reverse lookup hostname'],
] satisfies Array<readonly [string, string]>

const DEFAULT_ENDPOINT = endpoints[0]!

function PublicApiPage() {
  const [language, setLanguage] = React.useState('curl')
  const [serverUrl, setServerUrl] = React.useState(API_BASE)
  const [endpointPath, setEndpointPath] = React.useState(DEFAULT_ENDPOINT.path)
  const [params, setParams] = React.useState<Record<string, string>>(() => defaultsFor(DEFAULT_ENDPOINT))
  const [response, setResponse] = React.useState<ResponseState | null>(null)
  const [isSending, setIsSending] = React.useState(false)

  const endpoint = endpoints.find((item) => item.path === endpointPath) ?? DEFAULT_ENDPOINT
  const fullUrl = buildRequestUrl(serverUrl, endpoint, params)
  const codeExamples = React.useMemo(() => buildExamples(serverUrl, endpoint, params), [endpoint, params, serverUrl])

  function chooseEndpoint(nextPath: string) {
    const nextEndpoint = endpoints.find((item) => item.path === nextPath) ?? DEFAULT_ENDPOINT
    setEndpointPath(nextEndpoint.path)
    setParams(defaultsFor(nextEndpoint))
    setResponse(null)
  }

  function updateParam(name: string, value: string) {
    setParams((current) => ({ ...current, [name]: value }))
  }

  async function sendRequest() {
    setIsSending(true)
    setResponse(null)

    try {
      const result = await fetch(toBrowserRequestUrl(fullUrl), {
        method: endpoint.method,
        headers: { Accept: 'application/json' },
      })
      const contentType = result.headers.get('content-type') || 'text/plain'
      const text = await result.text()
      setResponse({
        status: result.status,
        contentType,
        body: formatBody(text, contentType),
      })
    } catch (error) {
      setResponse({
        status: 0,
        contentType: 'text/plain',
        body: error instanceof Error ? error.message : 'Request failed',
      })
    } finally {
      setIsSending(false)
    }
  }

  return (
    <div className="space-y-6">
      <PageHero
        variant="dark"
        eyebrow="Public API"
        title="DNS.NF Public API"
        badge="v1 · 60 req/min/IP"
        badgeTone="green"
        body={<>Query DNS records, reverse IP relationships, subdomains, rDNS records, DNS history, and DNSSEC data from {API_BASE}.</>}
        actions={
          <>
            <Button variant="secondary" size="sm" className="h-10 justify-center" onClick={() => copyText(markdownFor(endpoint, fullUrl, codeExamples.curl))}>
              <Clipboard className="h-4 w-4" />
              Copy Markdown
            </Button>
            <Button variant="secondary" size="sm" className="h-10 justify-center" onClick={() => openUrl(fullUrl)}>
              <ExternalLink className="h-4 w-4" />
              Open Request
            </Button>
          </>
        }
      />

      <Card>
        <CardHeader className="space-y-4 bg-zinc-50/70">
          <div>
            <div className="text-sm font-medium">Request Builder</div>
            <div className="mt-1 text-xs text-zinc-500">Choose an endpoint, edit parameters, then send a live request from this page.</div>
          </div>
          <div className="grid gap-3">
            <div className="grid gap-2">
              <label className="text-xs font-medium uppercase text-zinc-500">Server URL</label>
              <div className="flex min-w-0 items-center rounded-lg border border-zinc-200 bg-white p-1 shadow-sm shadow-zinc-200/50">
                <Input
                  value={serverUrl}
                  onChange={(event) => setServerUrl(event.target.value)}
                  className="h-9 border-0 bg-transparent font-mono focus:border-0 focus:ring-0"
                  aria-label="Server URL"
                />
                <Button variant="ghost" size="icon" className="h-8 w-8 shrink-0" aria-label="Copy server URL" onClick={() => copyText(serverUrl)}>
                  <Copy className="h-4 w-4" />
                </Button>
              </div>
            </div>
            <div className="grid gap-2">
              <label className="text-xs font-medium uppercase text-zinc-500">Endpoint</label>
              <Select
                value={endpoint.path}
                onValueChange={chooseEndpoint}
                options={endpoints.map((item) => ({ value: item.path, label: `${item.title} - ${item.path}` }))}
                ariaLabel="Endpoint"
              />
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-3">
            <div className="flex flex-wrap items-center gap-2">
              <StatusBadge tone="blue" className="font-mono">
                {endpoint.method}
              </StatusBadge>
              <code className="min-w-0 flex-1 break-all rounded-md bg-zinc-100 px-2 py-1 font-mono text-xs text-zinc-900">{endpoint.path}</code>
            </div>
            <p className="text-sm leading-6 text-zinc-600">{endpoint.description}</p>
            {endpoint.notes ? (
              <div className="grid gap-2">
                {endpoint.notes.map((note) => (
                  <div key={note} className="rounded-md border border-zinc-200 bg-zinc-50 px-3 py-2 text-xs leading-5 text-zinc-600">
                    {note}
                  </div>
                ))}
              </div>
            ) : null}
          </div>

          <section className="space-y-3">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <h2 className="text-lg font-semibold tracking-normal text-zinc-950">Parameters</h2>
              <Badge>Query String</Badge>
            </div>
            <div className="divide-y divide-zinc-100 rounded-lg border border-zinc-200">
              {endpoint.params.map((param) => (
                <div key={param.name} className="grid gap-3 p-4">
                  <div>
                    <div className="font-mono text-sm font-semibold text-zinc-950">
                      {param.name}
                      {param.required ? <span className="text-red-500">*</span> : null}{' '}
                      <span className="font-normal text-zinc-400">{param.type}</span>
                    </div>
                    <div className="mt-1 text-sm leading-6 text-zinc-600">{param.description}</div>
                  </div>
                  <Input value={params[param.name] ?? ''} onChange={(event) => updateParam(param.name, event.target.value)} />
                </div>
              ))}
            </div>
          </section>

          <section className="overflow-hidden rounded-lg border border-zinc-200 bg-white shadow-sm shadow-zinc-200/40">
            <div className="flex items-center gap-2 border-b border-zinc-100 px-3 py-2">
              <LinkIcon className="h-4 w-4 shrink-0 text-zinc-400" />
              <span className="min-w-0 flex-1 break-all font-mono text-xs text-zinc-600">{fullUrl}</span>
              <Button variant="ghost" size="icon" className="h-8 w-8 shrink-0" aria-label="Copy request URL" onClick={() => copyText(fullUrl)}>
                <Copy className="h-4 w-4" />
              </Button>
            </div>
            <div className="grid gap-3 bg-zinc-50/70 p-4">
              <div className="flex flex-wrap items-center gap-2">
                <StatusBadge tone={responseTone(response?.status)}>{response ? displayStatus(response.status) : 'Ready'}</StatusBadge>
                <span className="text-xs font-medium text-zinc-500">{response?.contentType || 'application/json'}</span>
                {response ? (
                  <Button variant="ghost" size="sm" className="ml-auto" onClick={() => setResponse(null)}>
                    <X className="h-4 w-4" />
                    Clear
                  </Button>
                ) : null}
              </div>
              <Button onClick={sendRequest} disabled={isSending} className="w-full">
                <Send className="h-4 w-4" />
                {isSending ? 'Sending' : 'Send Request'}
              </Button>
            </div>
            <pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words p-4 text-xs leading-6 text-zinc-800">
              {response?.body || '{\n  "message": "Click Send Request to run this endpoint from your browser."\n}'}
            </pre>
          </section>
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between bg-zinc-50/60">
          <div>
            <div className="text-sm font-medium">Code Examples</div>
            <div className="mt-1 text-xs text-zinc-500">Generated from the request builder.</div>
          </div>
          <Code2 className="h-4 w-4 text-zinc-400" />
        </CardHeader>
        <CardContent>
          <Tabs
            value={language}
            onValueChange={setLanguage}
            tabs={Object.entries(codeExamples).map(([key, code]) => ({
              value: key,
              label: languageLabels[key] ?? key,
              content: <CodeBlock code={code} />,
            }))}
          />
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between bg-zinc-50/60">
          <div>
            <div className="text-sm font-medium">Response Example</div>
            <div className="mt-1 text-xs text-zinc-500">Shape for the selected endpoint.</div>
          </div>
          <Button variant="ghost" size="icon" aria-label="Copy response example" onClick={() => copyText(endpoint.response)}>
            <Copy className="h-4 w-4" />
          </Button>
        </CardHeader>
        <CardContent>
          <CodeBlock code={endpoint.response} />
        </CardContent>
      </Card>

      <ReferenceSection title="Endpoints" description="All public endpoints are GET endpoints under https://api.dns.nf.">
        {endpoints.map((item) => (
          <EndpointCard key={item.path} endpoint={item} />
        ))}
      </ReferenceSection>

      <ReferenceSection title="DNS Record Types" description="Record types supported by the DNS lookup endpoint.">
        {recordRows.map(([type, meaning]) => (
          <InfoRow key={type} label={type} value={meaning} code />
        ))}
      </ReferenceSection>

      <ReferenceSection title="Response & Errors" description="Common response codes returned by the public API.">
        {errorRows.map(([code, meaning]) => (
          <InfoRow key={code} label={code} value={meaning} code={code === '200'} tone={code === '200' ? 'green' : code === '429' ? 'amber' : 'zinc'} />
        ))}
      </ReferenceSection>

      <blockquote className="rounded-lg border border-zinc-200 bg-white p-5 text-sm leading-6 text-zinc-600 shadow-sm shadow-zinc-200/40">
        DNS.NF queries public DNS infrastructure and public datasets. Reverse relationships and subdomain results are best-effort and may be incomplete or delayed.
      </blockquote>
    </div>
  )
}

function defaultsFor(endpoint: ApiEndpoint) {
  return Object.fromEntries(endpoint.params.map((param) => [param.name, param.defaultValue]))
}

function buildRequestUrl(baseUrl: string, endpoint: ApiEndpoint, params: Record<string, string>) {
  const cleanBase = baseUrl.replace(/\/+$/, '') || API_BASE
  const url = new URL(`${cleanBase}${endpoint.path}`, browserOrigin())

  endpoint.params.forEach((param) => {
    const value = params[param.name]?.trim()
    if (value) url.searchParams.set(param.name, value)
  })

  return url.toString()
}

function toBrowserRequestUrl(value: string) {
  if (typeof window === 'undefined' || !isLocalDevHost(window.location.hostname)) return value

  const url = new URL(value)
  if (url.hostname !== 'api.dns.nf') return value

  return `/api-proxy${url.pathname}${url.search}`
}

function buildExamples(baseUrl: string, endpoint: ApiEndpoint, params: Record<string, string>) {
  const url = buildRequestUrl(baseUrl, endpoint, params)
  const cleanBase = baseUrl.replace(/\/+$/, '') || API_BASE
  const queryPairs = endpoint.params
    .map((param) => [param.name, params[param.name]?.trim()] as const)
    .filter(([, value]) => Boolean(value))

  const jsParams = queryPairs.map(([key, value]) => `url.searchParams.set("${key}", "${escapeDouble(value || '')}");`).join('\n')
  const pyParams = queryPairs.map(([key, value]) => `        "${key}": "${escapeDouble(value || '')}",`).join('\n')
  const goParams = queryPairs.map(([key, value]) => `	q.Set("${key}", "${escapeDouble(value || '')}")`).join('\n')
  const phpParams = queryPairs.map(([key, value]) => `    "${key}" => "${escapeDouble(value || '')}",`).join('\n')
  const javaParams = queryPairs.map(([key, value]) => `    query.add("${key}=" + URLEncoder.encode("${escapeDouble(value || '')}", StandardCharsets.UTF_8));`).join('\n')

  return {
    curl: `curl -X ${endpoint.method} "${url}" \\
  -H "Accept: application/json"`,
    javascript: `const url = new URL("${cleanBase}${endpoint.path}");
${jsParams}

const response = await fetch(url, {
  headers: { "Accept": "application/json" },
});

if (!response.ok) throw new Error(await response.text());

const result = await response.json();
console.log(result);`,
    python: `import requests

response = requests.get(
    "${cleanBase}${endpoint.path}",
    params={
${pyParams}
    },
    headers={"Accept": "application/json"},
    timeout=10,
)
response.raise_for_status()

print(response.json())`,
    go: `package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"time"
)

func main() {
	u, _ := url.Parse("${cleanBase}${endpoint.path}")
	q := u.Query()
${goParams}
	u.RawQuery = q.Encode()

	client := &http.Client{Timeout: 10 * time.Second}
	req, _ := http.NewRequest("${endpoint.method}", u.String(), nil)
	req.Header.Set("Accept", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	var payload map[string]any
	if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
		panic(err)
	}
	fmt.Println(payload)
}`,
    php: `<?php
$url = "${cleanBase}${endpoint.path}?" . http_build_query([
${phpParams}
]);

$context = stream_context_create([
    "http" => [
        "header" => "Accept: application/json\\r\\n",
        "timeout" => 10,
    ],
]);

$json = file_get_contents($url, false, $context);
if ($json === false) {
    throw new RuntimeException("DNS.NF API request failed");
}

print_r(json_decode($json, true));`,
    java: `import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;

public class DnsNfExample {
  public static void main(String[] args) throws Exception {
    StringJoiner query = new StringJoiner("&");
${javaParams}
    String url = "${cleanBase}${endpoint.path}?" + query;

    HttpRequest request = HttpRequest.newBuilder()
      .uri(URI.create(url))
      .header("Accept", "application/json")
      .GET()
      .build();

    HttpResponse<String> response = HttpClient.newHttpClient()
      .send(request, HttpResponse.BodyHandlers.ofString());

    System.out.println(response.body());
  }
}`,
  }
}

function formatBody(text: string, contentType: string) {
  if (!text) return ''
  if (!contentType.includes('json')) return text

  try {
    return JSON.stringify(JSON.parse(text), null, 2)
  } catch {
    return text
  }
}

function responseTone(status?: number) {
  if (!status) return 'zinc'
  if (status >= 200 && status < 300) return 'green'
  if (status === 429) return 'amber'
  return 'red'
}

function displayStatus(status: number) {
  return status === 0 ? 'Network error' : String(status)
}

function escapeDouble(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function copyText(value: string) {
  if (typeof navigator !== 'undefined' && navigator.clipboard) {
    void navigator.clipboard.writeText(value)
  }
}

function openUrl(value: string) {
  if (typeof window !== 'undefined') {
    window.open(value, '_blank', 'noopener,noreferrer')
  }
}

function browserOrigin() {
  return typeof window === 'undefined' ? API_BASE : window.location.origin
}

function isLocalDevHost(hostname: string) {
  return hostname === 'localhost' || hostname === '127.0.0.1' || hostname === '::1'
}

function markdownFor(endpoint: ApiEndpoint, url: string, curl: string) {
  return `# ${endpoint.title}

${endpoint.description}

Base URL: ${API_BASE}
Website: ${WEBSITE}
Rate limit: 60 requests / minute / client IP

\`\`\`bash
${curl}
\`\`\`

Request URL:
${url}
`
}

function CodeBlock({ code }: { code: string }) {
  return (
    <div className="relative overflow-hidden rounded-lg border border-zinc-200 bg-zinc-950">
      <pre className="max-h-[420px] overflow-auto whitespace-pre-wrap break-words p-4 text-xs leading-6 text-zinc-50">{code}</pre>
    </div>
  )
}

function ReferenceSection({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return (
    <Card>
      <CardHeader className="bg-zinc-50/60">
        <div className="text-sm font-medium">{title}</div>
        <div className="mt-1 text-xs leading-5 text-zinc-500">{description}</div>
      </CardHeader>
      <CardContent className="grid gap-3">{children}</CardContent>
    </Card>
  )
}

function EndpointCard({ endpoint }: { endpoint: ApiEndpoint }) {
  return (
    <div className="rounded-lg border border-zinc-200 bg-white p-4">
      <div className="flex flex-wrap items-center gap-2">
        <StatusBadge tone="blue" className="font-mono">
          {endpoint.method}
        </StatusBadge>
        <code className="break-all rounded-md bg-zinc-100 px-1.5 py-1 font-mono text-xs text-zinc-900">{endpoint.path}</code>
      </div>
      <div className="mt-3 text-sm font-semibold text-zinc-950">{endpoint.title}</div>
      <div className="mt-1 text-sm leading-6 text-zinc-600">{endpoint.description}</div>
      <div className="mt-3 flex flex-wrap gap-2">
        {endpoint.params.map((param) => (
          <span key={param.name} className="rounded-md border border-zinc-200 bg-zinc-50 px-2 py-1 font-mono text-xs text-zinc-700">
            {param.name}
            {param.required ? '*' : ''}
          </span>
        ))}
      </div>
    </div>
  )
}

function InfoRow({ label, value, code = false, tone = 'zinc' }: { label: string; value: string; code?: boolean; tone?: 'zinc' | 'green' | 'amber' }) {
  return (
    <div className="rounded-lg border border-zinc-200 bg-white p-4">
      <div className="flex flex-wrap items-start gap-3">
        {code ? (
          <code className="rounded-md bg-zinc-100 px-1.5 py-1 font-mono text-xs text-zinc-900">{label}</code>
        ) : (
          <StatusBadge tone={tone}>{label}</StatusBadge>
        )}
        <div className="min-w-0 flex-1 text-sm leading-6 text-zinc-600">{value}</div>
      </div>
    </div>
  )
}

// pages/api.vue
<script setup lang="ts">
useSeoMeta({
  title: "API & Docs | DNS.NF",
  description:
    "DNS.NF API reference and documentation: endpoints, request examples, record types, and error codes for https://api.dns.nf.",
})

type FeatureRow = {
  name: string
  page: string
  api: string
  note: string
}

type EndpointRow = {
  method: "GET" | "POST"
  path: string
  query: string
  purpose: string
  limit: string
}

type RecordExplain = {
  type: string
  target: string
  useCase: string
}

type TerminalExample = {
  id: string
  label: string
  description: string
  endpoint: string
  query: string
  response: Record<string, unknown>
  origin?: string
}

type LanguageId = "curl" | "node" | "php" | "python" | "go" | "java"

type ErrorRow = {
  code: string
  meaning: string
}

const featureRows: FeatureRow[] = [
  {
    name: "DNS Lookup",
    page: "/dns-lookup",
    api: "/v1/dns/lookup",
    note: "A/AAAA/CNAME/MX/NS/SOA/SRV/TXT/CAA records for domain targets",
  },
  {
    name: "rDNS Scanner",
    page: "/rdns",
    api: "/v1/dns/rdns",
    note: "IPv4/CIDR concurrent scan, PTR+CNAME match modes, scoring and hint labels",
  },
  {
    name: "Reverse IP",
    page: "/reverse-ip",
    api: "/api/reverse-ip",
    note: "Find public domains pointing to one IPv4, with source labels + JSON/CSV export",
  },
  {
    name: "Reverse NS",
    page: "/reverse-ns",
    api: "/api/reverse-ns",
    note: "Find domains sharing authoritative NS servers",
  },
  {
    name: "Reverse MX",
    page: "/reverse-mx",
    api: "/api/reverse-mx",
    note: "Find domains sharing MX mail servers",
  },
  {
    name: "Subdomain Discovery",
    page: "/subdomains",
    api: "/api/subdomains",
    note: "Public host/subdomain discovery with source labels + JSON/CSV export",
  },
  {
    name: "DNSSEC",
    page: "/dnssec",
    api: "/api/dnssec",
    note: "DS / DNSKEY / RRSIG / NSEC checks with 0–100 security score and strong/partial/weak status",
  },
  {
    name: "DNS History",
    page: "/dns-history",
    api: "/v1/dns/history",
    note: "Read passive DNS records from CIRCL, Robtex, and local query history",
  },
]

const endpointRows: EndpointRow[] = [
  {
    method: "GET",
    path: "/v1/dns/lookup",
    query: "domain, type?",
    purpose: "Standard DNS lookup for domain targets",
    limit: "30 req/min per client IP",
  },
  {
    method: "GET",
    path: "/v1/dns/rdns",
    query: "target (ipv4|cidr)",
    purpose: "Concurrent reverse DNS scan with PTR/CNAME scoring",
    limit: "30s cooldown per client",
  },
  {
    method: "GET",
    path: "/api/reverse-ip",
    query: "ip",
    purpose: "Find public domains pointing to an IPv4",
    limit: "Public source dependent",
  },
  {
    method: "GET",
    path: "/api/reverse-ns",
    query: "domain, limit?",
    purpose: "Find domains sharing authoritative NS servers",
    limit: "Server-side capped and cached",
  },
  {
    method: "GET",
    path: "/api/reverse-mx",
    query: "domain, limit?",
    purpose: "Find domains sharing MX mail servers",
    limit: "Server-side capped and cached",
  },
  {
    method: "GET",
    path: "/api/subdomains",
    query: "domain",
    purpose: "Find public host records under target domain",
    limit: "Server-side capped and cached",
  },
  {
    method: "GET",
    path: "/api/dnssec",
    query: "domain",
    purpose: "DS/DNSKEY/RRSIG/NSEC checks with 0–100 security score",
    limit: "30 req/min per client IP",
  },
  {
    method: "GET",
    path: "/v1/dns/history",
    query: "domain, limit?",
    purpose: "Passive DNS history from CIRCL, Robtex, and local records",
    limit: "30 req/min per client IP",
  },
  {
    method: "GET",
    path: "/health",
    query: "(none)",
    purpose: "Health check endpoint",
    limit: "No token required",
  },
]

const recordExplainRows: RecordExplain[] = [
  { type: "A", target: "Domain", useCase: "IPv4 address mapping" },
  { type: "AAAA", target: "Domain", useCase: "IPv6 address mapping" },
  { type: "CNAME", target: "Domain", useCase: "Alias target chain" },
  { type: "MX", target: "Domain", useCase: "Mail server routing and priority" },
  { type: "NS", target: "Domain", useCase: "Authoritative name servers" },
  { type: "PTR", target: "IP/Domain(A/AAAA)", useCase: "Reverse lookup hostname" },
  { type: "SOA", target: "Domain", useCase: "Zone authority metadata" },
  { type: "SRV", target: "Domain", useCase: "Service endpoint target/port/priority" },
  { type: "TXT", target: "Domain", useCase: "Text policies and verification strings" },
  { type: "CAA", target: "Domain", useCase: "Allowed certificate authorities" },
  { type: "SPF / DMARC / DKIM", target: "TXT class", useCase: "Auto-grouped under TXT in this system" },
]

const examples: TerminalExample[] = [
  {
    id: "dns-all",
    label: "DNS ALL",
    description: "Lookup full standard record set for a domain",
    endpoint: "/v1/dns/lookup",
    query: "domain=microsoft.com&type=ALL",
    response: {
      code: 0,
      data: {
        domain: "microsoft.com",
        reverse_dns: ["13.107.253.44 r-0001.example.net"],
        records: {
          A: ["13.107.253.44", "13.107.226.44"],
          AAAA: ["2603:1030:b:3::152"],
          MX: [{ host: "microsoft-com.mail.protection.outlook.com", pref: 10 }],
          NS: ["ns1-39.azure-dns.com", "ns2-39.azure-dns.net"],
          TXT: ["SPF: v=spf1 include:spf.protection.outlook.com -all"],
        },
      },
      cached: false,
      timestamp: 1771545000,
    },
  },
  {
    id: "rdns-cidr",
    label: "rDNS CIDR",
    description: "Scan PTR/CNAME over CIDR with match filters",
    endpoint: "/v1/dns/rdns",
    query: "target=8.8.8.0/30&match_mode=middle&match_target=both",
    response: {
      code: 0,
      data: {
        target: "8.8.8.0/30",
        scanned: 2,
        with_ptr: 1,
        without_ptr: 1,
        results: [
          {
            ip: "8.8.8.1",
            ptr: ["dns.google"],
            cname: [],
            ok: true,
            residential_score: 30,
            hint: "datacenter_ptr_keyword",
            updated_at: "2026-02-20T06:15:20Z",
          },
        ],
      },
      cached: false,
      timestamp: 1771545050,
    },
  },
  {
    id: "reverse-ip",
    label: "Reverse IP",
    description: "Find public domains that resolve to one IPv4",
    endpoint: "/api/reverse-ip",
    origin: "https://dns.nf",
    query: "ip=8.8.8.8",
    response: {
      code: 0,
      data: {
        ip: "8.8.8.8",
        total: 2,
        domains: [
          { domain: "dns.google", sources: ["hackertarget"] },
          { domain: "resolver.google", sources: ["yougetsignal"] },
        ],
      },
      cached: true,
      timestamp: 1771545100,
    },
  },
  {
    id: "reverse-ns",
    label: "Reverse NS",
    description: "Find domains sharing authoritative NS",
    endpoint: "/api/reverse-ns",
    origin: "https://dns.nf",
    query: "domain=example.com&limit=20",
    response: {
      code: 0,
      data: {
        target: "example.com",
        ns: ["ns1.example-dns.com", "ns2.example-dns.com"],
        total_shared: 3,
        items: [
          {
            domain: "sample.net",
            shared_ns: ["ns1.example-dns.com"],
            source_ips: ["93.184.216.34"],
          },
        ],
      },
      cached: false,
      timestamp: 1771545150,
    },
  },
  {
    id: "reverse-mx",
    label: "Reverse MX",
    description: "Find domains sharing MX mail servers",
    endpoint: "/api/reverse-mx",
    origin: "https://dns.nf",
    query: "domain=example.com&limit=20",
    response: {
      code: 0,
      data: {
        target: "example.com",
        mx: ["mx1.example-mail.com"],
        total_shared: 2,
        items: [
          {
            domain: "sample.org",
            shared_mx: ["mx1.example-mail.com"],
            source_ips: ["203.0.113.10"],
          },
        ],
      },
      cached: false,
      timestamp: 1771545180,
    },
  },
  {
    id: "dns-history",
    label: "DNS History",
    description: "Passive DNS records from CIRCL, Robtex, and local query history",
    endpoint: "/v1/dns/history",
    query: "domain=cloudflare.com&limit=10",
    response: {
      code: 0,
      data: {
        domain: "cloudflare.com",
        records: [
          {
            type: "A",
            value: "104.16.133.229",
            first_seen: "2024-01-15T08:30:00Z",
            last_seen: "2026-02-20T12:00:00Z",
            source: "circl",
          },
          {
            type: "A",
            value: "104.16.132.229",
            first_seen: "2024-01-15T08:30:00Z",
            last_seen: "2026-02-20T12:00:00Z",
            source: "robtex",
          },
          {
            type: "AAAA",
            value: "2606:4700::6810:85e5",
            first_seen: "2024-03-10T14:20:00Z",
            last_seen: "2026-02-18T09:15:00Z",
            source: "local",
          },
        ],
        total: 3,
      },
      cached: true,
      timestamp: 1771545200,
    },
  },
]

const errorRows: ErrorRow[] = [
  { code: "200", meaning: "Success — response body contains code, data, cached, timestamp." },
  { code: "400", meaning: "Bad Request — missing or invalid query parameters." },
  { code: "404", meaning: "Not Found — no records found for the requested target." },
  { code: "429", meaning: "Too Many Requests — public rate limit or scan cooldown exceeded." },
  { code: "500", meaning: "Internal Server Error — upstream lookup failure." },
]

const languageTabs: Array<{ id: LanguageId; label: string }> = [
  { id: "curl", label: "cURL" },
  { id: "node", label: "Node.js" },
  { id: "php", label: "PHP" },
  { id: "python", label: "Python" },
  { id: "go", label: "Go" },
  { id: "java", label: "Java" },
]

const activeExampleId = ref(examples[0].id)
const activeLanguage = ref<LanguageId>("curl")
const terminalOutput = ref("")
const terminalRequest = ref("")
const typing = ref(false)
let timer: ReturnType<typeof setInterval> | null = null

const activeExample = computed(() => examples.find((x) => x.id === activeExampleId.value) || examples[0])
const activeLanguageLabel = computed(
  () => languageTabs.find((x) => x.id === activeLanguage.value)?.label || "cURL",
)

const escapeHtml = (value: string) =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;")

const highlightJson = (raw: string) => {
  const tokenRe =
    /("(?:\\.|[^"\\])*"(?=\s*:))|("(?:\\.|[^"\\])*")|\b(true|false|null)\b|\b-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b/g
  let out = ""
  let last = 0
  let match: RegExpExecArray | null
  while ((match = tokenRe.exec(raw)) !== null) {
    const token = match[0]
    const index = match.index
    out += escapeHtml(raw.slice(last, index))
    let cls = "token-default"
    if (match[1]) cls = "token-key"
    else if (match[2]) cls = "token-string"
    else if (match[3]) cls = "token-literal"
    else cls = "token-number"
    out += `<span class="${cls}">${escapeHtml(token)}</span>`
    last = index + token.length
  }
  out += escapeHtml(raw.slice(last))
  return out
}

const keywordRe =
  /\b(const|let|var|await|async|import|from|new|return|if|else|for|while|try|catch|defer|func|package|public|private|class|static|void|int|String|System|echo|print|true|false|null|nil)\b/
const punctuationRe = /[{}()[\].,:;]/

const highlightSource = (raw: string) => {
  const tokenRe =
    /("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')|\b-?\d+(?:\.\d+)?\b|\b(const|let|var|await|async|import|from|new|return|if|else|for|while|try|catch|defer|func|package|public|private|class|static|void|int|String|System|echo|print|true|false|null|nil)\b|[{}()[\].,:;]/g
  let out = ""
  let last = 0
  let match: RegExpExecArray | null
  while ((match = tokenRe.exec(raw)) !== null) {
    const token = match[0]
    const index = match.index
    out += escapeHtml(raw.slice(last, index))
    let cls = "token-default"
    if (token.startsWith('"') || token.startsWith("'")) cls = "token-string"
    else if (keywordRe.test(token)) cls = "token-keyword"
    else if (punctuationRe.test(token)) cls = "token-punc"
    else cls = "token-number"
    out += `<span class="${cls}">${escapeHtml(token)}</span>`
    last = index + token.length
  }
  out += escapeHtml(raw.slice(last))
  return out
}

const highlightedTerminalRequest = computed(() => highlightSource(terminalRequest.value))
const highlightedTerminalOutput = computed(() => highlightJson(terminalOutput.value))

const originText = () => "https://api.dns.nf"

const stopTyping = () => {
  if (timer) {
    clearInterval(timer)
    timer = null
  }
  typing.value = false
}

const buildRequestSnippet = (lang: LanguageId, endpoint: string, query: string, origin?: string) => {
  const url = `${origin || originText()}${endpoint}?${query}`
  switch (lang) {
    case "curl":
      return `curl -sS "${url}"`
    case "node":
      return [
        "const url = new URL(\"" + url + "\")",
        "",
        "const res = await fetch(url)",
        "const data = await res.json()",
        "console.log(JSON.stringify(data, null, 2))",
      ].join("\n")
    case "php":
      return [
        "$url = \"" + url + "\";",
        "$response = file_get_contents($url);",
        "$data = json_decode($response, true);",
        "echo json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . PHP_EOL;",
      ].join("\n")
    case "python":
      return [
        "import requests",
        "",
        "url = \"" + url + "\"",
        "resp = requests.get(url, timeout=15)",
        "print(resp.text)",
      ].join("\n")
    case "go":
      return [
        "resp, err := http.Get(\"" + url + "\")",
        "if err != nil {",
        "  log.Fatal(err)",
        "}",
        "defer resp.Body.Close()",
        "body, _ := io.ReadAll(resp.Body)",
        "fmt.Println(string(body))",
      ].join("\n")
    case "java":
      return [
        "HttpClient client = HttpClient.newHttpClient();",
        "HttpRequest request = HttpRequest.newBuilder()",
        "  .uri(URI.create(\"" + url + "\"))",
        "  .GET()",
        "  .build();",
        "HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());",
        "System.out.println(response.body());",
      ].join("\n")
    default:
      return `curl -sS "${url}"`
  }
}

const runExample = (id?: string) => {
  if (id) activeExampleId.value = id
  stopTyping()

  const selected = activeExample.value
  terminalRequest.value = buildRequestSnippet(activeLanguage.value, selected.endpoint, selected.query, selected.origin)

  const text = JSON.stringify(selected.response, null, 2)
  terminalOutput.value = ""
  typing.value = true

  let index = 0
  timer = setInterval(() => {
    index += 2
    terminalOutput.value = text.slice(0, index)
    if (index >= text.length) {
      stopTyping()
    }
  }, 8)
}

onMounted(() => runExample(activeExampleId.value))
onBeforeUnmount(() => stopTyping())
</script>

<template>
  <section class="page-container docs-page">
    <section class="docs-hero">
      <h1><i class="fa-solid fa-book-open" aria-hidden="true"></i> API & Documentation</h1>
      <p>
        Live reference for DNS.NF endpoints, record types, and usage examples. Base URL:
        <code class="inline-code">https://api.dns.nf</code>
      </p>
      <div class="docs-badges">
        <span class="docs-badge"><i class="fa-solid fa-gauge-high" aria-hidden="true"></i> DNS Lookup: 30 req/min per IP</span>
        <span class="docs-badge"><i class="fa-solid fa-satellite-dish" aria-hidden="true"></i> rDNS: 30s cooldown per client</span>
        <span class="docs-badge"><i class="fa-solid fa-unlock-keyhole" aria-hidden="true"></i> Public queries: no token required</span>
        <span class="docs-badge"><i class="fa-solid fa-database" aria-hidden="true"></i> Passive DNS from public datasets</span>
      </div>
    </section>

    <section class="docs-card">
      <div class="section-head">
        <h2><i class="fa-solid fa-table" aria-hidden="true"></i> Feature Matrix</h2>
      </div>
      <div class="docs-table-wrap">
        <table class="docs-table feature-matrix-table">
          <thead>
            <tr>
              <th>Feature</th>
              <th>Page</th>
              <th>API</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in featureRows" :key="row.name">
              <td>{{ row.name }}</td>
              <td><code>{{ row.page }}</code></td>
              <td><code>{{ row.api }}</code></td>
              <td>{{ row.note }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <section class="docs-card">
      <div class="section-head">
        <h2><i class="fa-solid fa-plug" aria-hidden="true"></i> API Endpoints</h2>
      </div>
      <div class="docs-table-wrap">
        <table class="docs-table endpoints-table">
          <thead>
            <tr>
              <th>Method</th>
              <th>Path</th>
              <th>Query</th>
              <th>Purpose</th>
              <th>Limit / Rule</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in endpointRows" :key="row.path + row.method">
              <td><span class="method-pill">{{ row.method }}</span></td>
              <td><code>{{ row.path }}</code></td>
              <td class="query-col">{{ row.query }}</td>
              <td>{{ row.purpose }}</td>
              <td>{{ row.limit }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p class="endpoint-note">
        Public query endpoints do not require an API token. Some endpoints are rate limited or capped to keep the free service available.
      </p>
    </section>

    <section class="docs-card terminal-card">
      <div class="section-head">
        <h2><i class="fa-solid fa-terminal" aria-hidden="true"></i> Interactive Terminal Demo</h2>
      </div>
      <div class="terminal-lang-tabs">
        <button
          v-for="tab in languageTabs"
          :key="tab.id"
          type="button"
          class="terminal-lang-tab"
          :class="{ 'is-active': activeLanguage === tab.id }"
          @click="activeLanguage = tab.id; runExample()"
        >
          {{ tab.label }}
        </button>
      </div>
      <div class="terminal-layout">
        <div class="terminal-example-list">
          <button
            v-for="item in examples"
            :key="item.id"
            type="button"
            class="terminal-example-btn"
            :class="{ 'is-active': activeExampleId === item.id }"
            @click="runExample(item.id)"
          >
            <span class="terminal-example-title">{{ item.label }}</span>
            <span class="terminal-example-desc">{{ item.description }}</span>
          </button>
        </div>

        <div class="terminal-shell">
          <div class="terminal-head">
            <span>{{ activeLanguageLabel }} Example</span>
            <button type="button" class="run-btn" @click="runExample()">
              <i class="fa-solid fa-play" aria-hidden="true"></i> Run
            </button>
          </div>
          <pre class="terminal-command"><code class="terminal-code" v-html="highlightedTerminalRequest"></code></pre>
          <pre class="terminal-output"><code class="terminal-code" v-html="highlightedTerminalOutput"></code><span v-if="typing" class="cursor">|</span></pre>
        </div>
      </div>
    </section>

    <section class="docs-card">
      <div class="section-head">
        <h2><i class="fa-solid fa-list-check" aria-hidden="true"></i> Record Types And Meaning</h2>
      </div>
      <div class="docs-table-wrap">
        <table class="docs-table">
          <thead>
            <tr>
              <th>Type</th>
              <th>Target</th>
              <th>What It Means</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in recordExplainRows" :key="row.type">
              <td><code>{{ row.type }}</code></td>
              <td>{{ row.target }}</td>
              <td>{{ row.useCase }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <section class="docs-card">
      <div class="section-head">
        <h2><i class="fa-solid fa-triangle-exclamation" aria-hidden="true"></i> Response &amp; Errors</h2>
      </div>
      <div class="docs-table-wrap">
        <table class="docs-table">
          <thead>
            <tr>
              <th>HTTP Code</th>
              <th>Meaning</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in errorRows" :key="row.code">
              <td><code>{{ row.code }}</code></td>
              <td>{{ row.meaning }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p class="endpoint-note">
        All JSON responses share the same shape:
        <code>{ code: number, data: any, cached: boolean, timestamp: number }</code>.
      </p>
    </section>

    <blockquote class="privacy-quote">
      <i class="fa-solid fa-shield-halved privacy-quote-icon" aria-hidden="true"></i>
      <span>DNS.NF queries only publicly available DNS data and public datasets. Some results may be incomplete or delayed.</span>
    </blockquote>
  </section>
</template>

<style scoped>
.docs-page {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.privacy-quote {
  margin-top: 10px;
}

.docs-hero,
.docs-card {
  border: 1px solid var(--panel-border);
  background: #ffffff;
  padding: 16px;
  border-radius: 0;
}

.docs-hero h1 {
  margin: 0;
  color: #1E293B;
  font-size: 24px;
  display: inline-flex;
  align-items: center;
  gap: 10px;
}

.docs-hero p {
  margin-top: 8px;
  color: #64748B;
  font-size: 14px;
}

.inline-code {
  background: #f4f6f8;
  border: 1px solid var(--panel-border);
  color: #1E293B;
  font-size: 13px;
  padding: 2px 6px;
}

.docs-badges {
  margin-top: 12px;
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.docs-badge {
  min-height: 30px;
  border: 1px solid var(--panel-border);
  background: #f8f9fa;
  color: #495057;
  font-size: 12px;
  font-weight: 600;
  display: inline-flex;
  align-items: center;
  gap: 7px;
  padding: 0 10px;
}

.section-head {
  margin-bottom: 10px;
}

.section-head h2 {
  margin: 0;
  color: #1E293B;
  font-size: 19px;
  display: inline-flex;
  align-items: center;
  gap: 9px;
}

.docs-table-wrap {
  border: 1px solid var(--panel-border);
  overflow-x: hidden;
}

.docs-table {
  width: 100%;
  border-collapse: collapse;
  table-layout: fixed;
}

.docs-table th,
.docs-table td {
  border-bottom: 1px solid var(--panel-border);
  padding: 10px;
  vertical-align: top;
  text-align: left;
  color: #1E293B;
  font-size: 13px;
  line-height: 1.45;
}

.endpoints-table th:nth-child(1),
.endpoints-table td:nth-child(1) { width: 80px; }
.endpoints-table th:nth-child(2),
.endpoints-table td:nth-child(2) { width: 180px; }
.endpoints-table th:nth-child(3),
.endpoints-table td:nth-child(3) { width: 150px; }
.endpoints-table th:nth-child(4),
.endpoints-table td:nth-child(4) { width: 400px; }
.endpoints-table th:nth-child(5),
.endpoints-table td:nth-child(5) { width: auto; }

.feature-matrix-table th:nth-child(1),
.feature-matrix-table td:nth-child(1) { width: 180px; }
.feature-matrix-table th:nth-child(2),
.feature-matrix-table td:nth-child(2) { width: 150px; }
.feature-matrix-table th:nth-child(3),
.feature-matrix-table td:nth-child(3) { width: 160px; }
.feature-matrix-table th:nth-child(4),
.feature-matrix-table td:nth-child(4) { width: auto; }

.docs-table th {
  background: #f8f9fa;
  color: #64748B;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.03em;
}

.docs-table tr:last-child td {
  border-bottom: none;
}

.docs-table code,
.endpoint-note code {
  background: #f4f6f8;
  border: 1px solid var(--panel-border);
  color: #1E293B;
  font-size: 12px;
  padding: 2px 6px;
  white-space: normal;
  overflow-wrap: anywhere;
  word-break: break-word;
}

.query-col {
  overflow-wrap: anywhere;
  word-break: break-word;
}

.method-pill {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 24px;
  min-width: 44px;
  border: 1px solid #8ed8ab;
  background: #e9f7ef;
  color: var(--app-accent);
  font-weight: 700;
  font-size: 11px;
  padding: 0 8px;
}

.endpoint-note {
  margin-top: 10px;
  color: #64748B;
  font-size: 13px;
}

.terminal-card {
  overflow: hidden;
}

.terminal-lang-tabs {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 12px;
}

.terminal-lang-tab {
  min-height: 32px;
  border: 1px solid var(--panel-border);
  background: #ffffff;
  color: #495057;
  font-size: 12px;
  font-weight: 700;
  padding: 0 12px;
  cursor: pointer;
}

.terminal-lang-tab.is-active {
  border-color: var(--app-accent);
  color: var(--app-accent);
  background: #eaf7ef;
}

.terminal-layout {
  display: grid;
  grid-template-columns: 300px minmax(0, 1fr);
  gap: 12px;
  align-items: stretch;
}

.terminal-example-list {
  border: 1px solid var(--panel-border);
  background: #ffffff;
  padding: 8px;
  display: grid;
  gap: 8px;
  height: 420px;
  overflow: auto;
}

.terminal-example-btn {
  border: 1px solid var(--panel-border);
  background: #ffffff;
  color: #1E293B;
  text-align: left;
  padding: 8px;
  cursor: pointer;
  display: grid;
  gap: 3px;
}

.terminal-example-btn.is-active {
  border-color: var(--app-accent);
  background: #eaf7ef;
}

.terminal-example-title {
  font-size: 13px;
  font-weight: 700;
}

.terminal-example-desc {
  font-size: 12px;
  color: #64748B;
}

.terminal-shell {
  border: 1px solid var(--panel-border);
  background: #0f172a;
  color: #dbeafe;
  height: 420px;
  display: flex;
  flex-direction: column;
}

.terminal-head {
  min-height: 40px;
  border-bottom: 1px solid #1e293b;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 12px;
  font-size: 12px;
  color: #93c5fd;
}

.run-btn {
  border: 1px solid #2f855a;
  background: var(--app-accent);
  color: #ffffff;
  min-height: 28px;
  padding: 0 10px;
  font-size: 12px;
  font-weight: 700;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  gap: 6px;
}

.run-btn:hover {
  filter: brightness(0.95);
}

.terminal-command {
  margin: 0;
  padding: 10px 12px;
  border-bottom: 1px solid #1e293b;
  font-size: 12px;
  line-height: 1.5;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}

.terminal-output {
  margin: 0;
  padding: 12px;
  flex: 1;
  font-size: 12px;
  line-height: 1.5;
  white-space: pre-wrap;
  overflow: auto;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
}

.terminal-code {
  display: block;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}

.terminal-shell :deep(.token-default) {
  color: #dbeafe;
}

.terminal-shell :deep(.token-keyword) {
  color: var(--app-accent);
  font-weight: 600;
}

.terminal-shell :deep(.token-key),
.terminal-shell :deep(.token-string) {
  color: #86efac;
}

.terminal-shell :deep(.token-number) {
  color: #facc15;
}

.terminal-shell :deep(.token-literal) {
  color: #60a5fa;
  font-weight: 600;
}

.terminal-shell :deep(.token-punc) {
  color: #94a3b8;
}

html[data-theme="light"] .terminal-shell :deep(.token-default) {
  color: #e2e8f0;
}

html[data-theme="light"] .terminal-shell :deep(.token-keyword) {
  color: var(--app-accent);
}

html[data-theme="light"] .terminal-shell :deep(.token-key),
html[data-theme="light"] .terminal-shell :deep(.token-string) {
  color: #bbf7d0;
}

html[data-theme="light"] .terminal-shell :deep(.token-number) {
  color: #fde68a;
}

html[data-theme="light"] .terminal-shell :deep(.token-literal) {
  color: #93c5fd;
}

html[data-theme="light"] .terminal-shell :deep(.token-punc) {
  color: #cbd5e1;
}

html[data-theme="dark"] .terminal-shell :deep(.token-default) {
  color: #EBEBEB;
}

html[data-theme="dark"] .terminal-shell :deep(.token-keyword) {
  color: var(--app-accent);
}

html[data-theme="dark"] .terminal-shell :deep(.token-key),
html[data-theme="dark"] .terminal-shell :deep(.token-string) {
  color: #86efac;
}

html[data-theme="dark"] .terminal-shell :deep(.token-number) {
  color: #facc15;
}

html[data-theme="dark"] .terminal-shell :deep(.token-literal) {
  color: #60a5fa;
}

html[data-theme="dark"] .terminal-shell :deep(.token-punc) {
  color: #94a3b8;
}

.cursor {
  color: #86efac;
  animation: blink 0.9s steps(1) infinite;
}

@keyframes blink {
  50% {
    opacity: 0;
  }
}

@media (max-width: 1024px) {
  .terminal-layout {
    grid-template-columns: 1fr;
  }

  .terminal-shell {
    height: 320px;
  }

  .terminal-example-list {
    height: auto;
    overflow: visible;
  }
}
</style>
